<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\QarzAlHasana.Application\QarzAlHasana.Application.csproj" />
      <ProjectReference Include="..\QarzAlHasana.Domain\QarzAlHasana.Domain.csproj" />
    </ItemGroup>

</Project>
